version: '3.7'
services:
  app_prod:
    build:
      context: .
      target: production
    #image: cekta/demo:app
  nginx:
    build:
      context: .
    #image: cekta/demo:nginx
  migration:
    build:
      context: .
      target: migration
    #image: cekta/demo:migration
